travis:
  secure:
    BINSTAR_TOKEN: jaKhVCvjEDdDjR3TPKtCx86PONY+O1YfDIaa7vIi1XAsbEbdRwMISIgio5idk8nzKHGBzQSbc3wRVkEtRybks/KPP2Ov9EWBNCIt2/XdG2zDMuPjP3jUqNCXgGT7e42JtyqQlViIDRQBfhE2atN40uSOPC1Lwrhg4YkODeo8W6h//VlHCywEXukoo6FTrTVh6o9YiuVgATuc+Lp+Vt/J3P+n9koNdz6WTnpcKm7o2zrInVzFIX6lS0cJOy1P7vbgGvLCjqD8P/Lq0dTetDCnnAt6odjGatwhvNYne5/YbWfOP/w2VzXbsEICJdjf/6a9rn+lUOXYBjcQMH4QFe9MU+O2JhkkkIl/MyQ2f2MJCsIV9aLadTttUCT6OBBL93Cd9d6VIzjmX2PUdELL2TORkAZ9afj6YOlcedOPEVKQ3QDglAOD6q/yJPn3SvIimBR/1AH78zILPCPJ/YTeDuEyugm/vrSNB9Cht/b6j2Db9RL7mlQ9sEeTzpXv5oLjHhJAyn65/8e0lfMfITd4tuu1EWtbLjsTlBv7X+NDRIIqLzg3WzDUPLQe8ZC61gw+31cXYRc0MSpHQistOG7J/G+C3gm83bGNIZm8LBzlh1zsqCVX4RUxnhsPfncEZk+6Jh/qzf2fTN8ovzd89OArr7hDg/z1k+58a7E/6WrVuSTsH38=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
